name: Lint with registered Docker Image
on:
  push:
    branches:
      - main
    paths:
      - "!contrib/*"
      - "!tools/*"
      - "!go.mod"
  pull_request:
    paths:
      - "!contrib/*"
      - "!tools/*"
      - "!go.mod"
  workflow_call:
    inputs:
      CACHE_DIR:
        required: false
        type: string
      CACHE_FILE:
        required: false
        type: string
      TAG:
        required: false
        type: string

jobs:
  lint-with-registerd-docker-image:
    runs-on: ubuntu-latest
    if: ${{ inputs.CACHE_FILE == '' }}
    container:
      image: line/tm-db-testing
      env:
        CGO_LDFLAGS: -lrocksdb
      credentials:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - uses: actions/checkout@v3
      - name: lint
        run: |
          golangci-lint run -v --build-tags 'cleveldb,rocksdb,boltdb,badgerdb'

  lint:
    runs-on: ubuntu-latest
    if: ${{ inputs.CACHE_FILE != '' }}
    steps:
      - uses: actions/checkout@v3

      - name: Cache Docker Image
        id: cache
        uses: actions/cache@v3
        with:
          path: ${{ inputs.CACHE_DIR }}
          key: ${{ inputs.CACHE_FILE }}

      - name: Load Docker Image
        run: |
          docker load -i ${{ inputs.CACHE_FILE }}

      - name: lint
        run: |
          docker run -e CGO_LDFLAGS=-lrocksdb --rm -v "$(pwd)":/workspace -w /workspace ${{ inputs.TAG }} bash -c "\
          golangci-lint run -v --build-tags 'cleveldb,rocksdb,boltdb,badgerdb' \
          "
